---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-statefulset-password
type: opaque
stringData:
  MYSQL_ROOT_PASSWORD: password

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: mysql

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-statefulset-sc
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-stateful-pv-0
  labels:
    type: local
spec:
  storageClassName: mysql-statefulset-sc
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-stateful-pv-1
  labels:
    type: local
spec:
  storageClassName: mysql-statefulset-sc
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-stateful-pv-2
  labels:
    type: local
spec:
  storageClassName: mysql-statefulset-sc
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-statefulset-service"
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-store
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.2"
          limits:
            memory: "768Mi"
            cpu: "0.5"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-statefulset-password
              key: MYSQL_ROOT_PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: mysql-store
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "mysql-statefulset-sc"
      resources:
        requests:
          storage: 300Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  labels:
    name: mysql-client
spec:
  containers:
  - name: mysql-client
    image: alpine:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.5"
    command: ['sh','-c', "sleep 1800m"]
    imagePullPolicy: IfNotPresent
