---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-pv
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30001
    name: nginx-external-port
  selector:
    app: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-pv
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Europe/Moscow
          type: File
      - name: html
        emptyDir: {}
      - name: stateful-pv
        persistentVolumeClaim:
          claimName: stateful-pv-claim
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: stateful-pv
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: alpine
        volumeMounts:
        - name: stateful-pv
          mountPath: /html
        - name: tz-config
          mountPath: /etc/localtime
        image: alpine:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ["/bin/sh", "-c"]
        args:
          - while true; do
              date > /html/index.html;
              sleep 1;
            done
