---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-pv-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
